import os
import sys

def find_crossover(time, signal, target, direction, t_start, t_end):
    """
    Finds the interpolated timestamp when the signal crosses the target value
    in a given direction within a specific time window.
    """
    # Filter indices that fall within the time window
    indices = [i for i in range(len(time)) if t_start <= time[i] <= t_end]
    
    if not indices:
        raise ValueError(f"No simulation points found in time window [{t_start}, {t_end}]")

    for idx in indices[:-1]:
        v1, v2 = signal[idx], signal[idx+1]
        t1, t2 = time[idx], time[idx+1]
        
        if direction == 'rising':
            if v1 <= target <= v2:
                if v2 != v1:
                    return t1 + (t2 - t1) * (target - v1) / (v2 - v1)
                return t1
        elif direction == 'falling':
            if v1 >= target >= v2:
                if v2 != v1:
                    return t1 + (t2 - t1) * (target - v1) / (v2 - v1)
                return t1
                
    raise ValueError(
        f"Target value {target} not crossed in direction '{direction}' "
        f"within window [{t_start}, {t_end}]. Signal range: [{min([signal[i] for i in indices]):.3f}, {max([signal[i] for i in indices]):.3f}]"
    )

def parse_simulation_data(file_path, vdd=1.8):
    """
    Reads tabular data generated by wrdata and computes:
    - cell_rise
    - cell_fall
    - rise_transition
    - fall_transition
    """
    if not os.path.exists(file_path):
        raise FileNotFoundError(f"Simulation output file not found at {file_path}")
        
    time = []
    v_in = []
    v_out = []
    
    with open(file_path, 'r') as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            parts = line.split()
            if len(parts) >= 4:
                # Format: time_val v(in)_val time_val v(out)_val
                try:
                    time.append(float(parts[0]))
                    v_in.append(float(parts[1]))
                    v_out.append(float(parts[3]))
                except ValueError:
                    # Skip any headers or malformed lines
                    continue
                    
    if not time:
        raise ValueError("No valid data points read from simulation output file.")
        
    val_10 = 0.1 * vdd
    val_50 = 0.5 * vdd
    val_90 = 0.9 * vdd
    
    # Dynamically detect when the input signal transitions to auto-define windows.
    # 1. Locate the first rising edge of the input (goes above 50% VDD)
    t_in_rise_rough = None
    for i in range(1, len(time)):
        if v_in[i-1] < val_50 <= v_in[i]:
            t_in_rise_rough = time[i]
            break
            
    if t_in_rise_rough is None:
        # Fallback to hardcoded window if no rising edge is found
        print("Warning: Input rising edge not detected. Falling back to default window.")
        t_start_fall = 0.5e-9
        t_end_fall = 5.0e-9
    else:
        # Define window centered around the input rising edge (which causes output falling)
        t_start_fall = max(0.0, t_in_rise_rough - 0.5e-9)
        t_end_fall = t_in_rise_rough + 4.0e-9

    # 2. Locate the first falling edge of the input (goes below 50% VDD, starting after the rising edge window)
    t_in_fall_rough = None
    search_start_time = t_start_fall + 4.5e-9
    for i in range(1, len(time)):
        if time[i] >= search_start_time:
            if v_in[i-1] > val_50 >= v_in[i]:
                t_in_fall_rough = time[i]
                break

    if t_in_fall_rough is None:
        # Fallback to hardcoded window if no falling edge is found
        print("Warning: Input falling edge not detected. Falling back to default window.")
        t_start_rise = 10.5e-9
        t_end_rise = 15.0e-9
    else:
        # Define window centered around the input falling edge (which causes output rising)
        t_start_rise = t_in_fall_rough - 0.5e-9
        t_end_rise = t_in_fall_rough + 4.0e-9

    # Solve crossovers
    t_in_rise_50 = find_crossover(time, v_in, val_50, 'rising', t_start_fall, t_end_fall)
    t_out_fall_90 = find_crossover(time, v_out, val_90, 'falling', t_start_fall, t_end_fall)
    t_out_fall_50 = find_crossover(time, v_out, val_50, 'falling', t_start_fall, t_end_fall)
    t_out_fall_10 = find_crossover(time, v_out, val_10, 'falling', t_start_fall, t_end_fall)
    
    cell_fall = t_out_fall_50 - t_in_rise_50
    fall_transition = t_out_fall_10 - t_out_fall_90
    
    t_in_fall_50 = find_crossover(time, v_in, val_50, 'falling', t_start_rise, t_end_rise)
    t_out_rise_10 = find_crossover(time, v_out, val_10, 'rising', t_start_rise, t_end_rise)
    t_out_rise_50 = find_crossover(time, v_out, val_50, 'rising', t_start_rise, t_end_rise)
    t_out_rise_90 = find_crossover(time, v_out, val_90, 'rising', t_start_rise, t_end_rise)
    
    cell_rise = t_out_rise_50 - t_in_fall_50
    rise_transition = t_out_rise_90 - t_out_rise_10
    
    return {
        'cell_rise': cell_rise,
        'cell_fall': cell_fall,
        'rise_transition': rise_transition,
        'fall_transition': fall_transition
    }

if __name__ == '__main__':
    # Simple standalone check
    if len(sys.argv) > 1:
        file_path = sys.argv[1]
        try:
            results = parse_simulation_data(file_path)
            for k, v in results.items():
                print(f"{k}: {v * 1e12:.2f} ps")
        except Exception as e:
            print(f"Error parsing file: {e}")
            sys.exit(1)
